version: '2.7'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php public/index.php'
    relay: pipes
    env:
        APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
kv:
    local:
        driver: memory
        config:
            interval: 60
#    redis:
#        driver: redis
#        config:
#            addrs:
#                - 'localhost:6379'
metrics:
    address: 'localhost:2112'
